name: karasing-infra
description: Infra BigQuery Sandbox KaraSing
runtime:
  name: python
  options:
    toolchain: pip
    virtualenv: venv
config:
  pulumi:tags:
    value:
      pulumi:template: gcp-python
